version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: docker/base/Dockerfile
    image: sdn-project-base:latest
    privileged: true
    network_mode: host
    container_name: sdn-project-base

  pox:
    build:
      context: .
      dockerfile: docker/pox/Dockerfile
    image: sdn-project-pox:latest
    privileged: true
    network_mode: host
    container_name: sdn-project-pox
    depends_on:
      - base

  mininet:
    build:
      context: .
      dockerfile: docker/mininet/Dockerfile
    image: sdn-project-mininet:latest
    privileged: true
    network_mode: host
    container_name: sdn-project-mininet
    depends_on:
      - base
      - pox 